### ISSUE TITLE
Develop Pipe class

### ISSUE THREAD

**Issue by koyuul** [Cube-3-San-Jose-State/hoplite#15]
**Objective:**
Convert a struct into reusable C++ pipe class that we can utilize to communicate between different processes.

**Purpose:**
We are using named pipes to communicate between different processes. In order to avoid re-implementing the same struct, we need a .h library and .cpp implementation for our current piping struct.

**Current code written:**
Currently, we have a struct in [the command handler program](https://github.com/Cube-3-San-Jose-State/hoplite/blob/main/HeadBoard/CommandHandler.cpp). We will need these variables, as well as a listen() function and a send() function in the class. The end goal is to have a class that we can #include, provide a path, and utilize to send messages back and forth.

If more context/info is needed please reach out!

Also, [this tutorial](https://www.geeksforgeeks.org/named-pipe-fifo-example-c-program/) was referenced in creating the current pipe implementation.

**Comment by GreenMoonMan** [comment]
### Some research notes
- Here is a good resource that explains in depth how pipes work: https://opensource.com/article/19/4/interprocess-communication-linux-channels
- There are also other IPC methods which may be more suited for bidirectional communication such as sockets: https://opensource.com/article/19/4/interprocess-communication-linux-networking
- Planning on going the pipe route since it seems simpler
- To see what is written to a pipe, just use the `cat` command on the pipe file.
